stages:
  - build
  - deploy
# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache

variables:
  IMAGE_NAME: docker.jokuna.local/dev/wooman

cache:
  paths:
    - node_modules/

build:
  stage: build
  before_script:
  - docker login docker.jokuna.local -u kuna -p $REGISTRY_TOKEN
  script:
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME
  only:
    - master  
  tags:
    - build

deploy:
  stage: deploy
  before_script:
    - docker login docker.jokuna.local -u kuna -p $REGISTRY_TOKEN
  script:
    - docker container rm -f wooman && docker rmi $IMAGE_NAME
    - docker-compose up -d
    # docker run -d --name wooman --restart always $IMAGE_NAME
  only:
    - master
  tags:
    - deploy