image: node:14.16.0
stages:
  - build
  - deploy
# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
build:
  tag: deploy
  stage: build
  script:
    - yarn install && yarn global add pm2
  only:
    - master
deploy:
  tag: deploy
  stage: deploy
  extends: build
  only:
    - master
  script:
    - yarn pm2