stages:
  - build
  - deploy
# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache

variables:
  IMAGE_NAME: docker.jokuna.local/dev/wooman

cache:
  paths:
    - node_modules/

# Local에서 Image Build

build:
  stage: build
  before_script:
  - docker login docker.jokuna.local -u kuna -p $REGISTRY_TOKEN
  script:
    - echo 'Building...'
    - ls -al && pwd
    - docker info
    - docker container ls -a
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME
    - docker images
  only:
    - master  
  tags:
    - build


# build:
#   tags:
#     - deploy
#   stage: build
#   script:
#     - yarn add global pm2 && yarn install
#   only:
#     - master

deploy:
  stage: deploy
  before_script:
    - docker login docker.jokuna.local -u kuna -p $REGISTRY_TOKEN
  script:
    - echo 'Deploying...'
    - docker container ls -a
    - docker container rm -f wooman
    - docker run -d --name wooman --restart always $IMAGE_NAME
    - docker container ls -a
  only:
    - master
  tags:
    - deploy